# Generated by Django 4.2.7 on 2024-02-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0002_alter_termin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='rent_timeframe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
