# Generated by Django 4.2.7 on 2024-02-20 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('termine', '0004_remove_termin_notes_termin_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='termine',
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termin',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='termin',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termin',
            name='taken_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='termin',
            name='notes',
        ),
        migrations.AddField(
            model_name='termin',
            name='notes',
            field=models.ManyToManyField(blank=True, to='termine.note'),
        ),
    ]
