# Generated by Django 4.2.7 on 2024-02-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0005_remove_note_termine_note_created_by_termin_is_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='termin',
            name='notes',
        ),
        migrations.AddField(
            model_name='termin',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
