# Generated by Django 4.2.7 on 2024-02-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('termine', '0006_remove_note_created_by_remove_termin_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termin',
            name='taken_by',
        ),
    ]
